Updates: Android and workflows
RHVoice/RHVoice pull request #627
Opened 2022-09-20 01:17 UTC by PatrykMis

#### Android: build changes

Bumps:

* Android Gradle Plugin
* Desugar
* CURL
* Moshi

Enhancements:

* Add BuildTools version

Deprecations:

* move away from deprecated `package` attribute
* avoid deprecated functions and attributes

Fixes:

* Define ext.myNdkVersion and move it to proper place

#### Others

* Update CI
* Add Gradle Wrapper Validation Action

2022-09-20 15:11 UTC, zstanecic commented
great to see that you hopefully state the license.
Please state this in 
#556

2022-09-20 16:21 UTC, zstanecic commented
@PatrykMis 
are you going also to implement direct boot support?

2022-09-22 17:14 UTC, alex19EP requested changes

2022-09-22 20:40 UTC, PatrykMis commented on .github/workflows/ci.yml
> +          java-version: '18'
Java 18 at the moment is the latest stable version. It's obviously capable of running code designed for earlier versions while we can use latest runtime improvements. Note that source and target attributes are still 11, so it is mainly the runtime thing.
After all these changes (including gradle caching) Android build task times (also visible in Github actions) are decreased though.

2022-09-22 20:46 UTC, PatrykMis commented on .github/workflows/ci.yml
> +        run: ./gradlew assembleDebug --stacktrace --no-daemon
[As stated in the Gradle's manual](https://docs.gradle.org/current/userguide/performance.html#enable_the_daemon_on_old_gradle_versions) daemon increases performance only when running more tasks than just one (like in our case). Each workflow we are running on a fresh machine though. It's also better for security to "fork [our] daemon".

2022-10-04 22:05 UTC, alex19EP commented on .github/workflows/ci.yml
> +        run: ./gradlew assembleDebug --stacktrace --no-daemon
ok thanks

2022-10-04 22:11 UTC, alex19EP requested changes
one more thing and good to merge.

2022-10-04 22:11 UTC, alex19EP commented on .github/workflows/ci.yml
> +          python-version: '3.10'
pleas fix this

2022-10-09 21:32 UTC, PatrykMis commented on .github/workflows/ci.yml
> +          python-version: '3.10'
Python 3.7 is almost in eol (end of life) state. Is it really nessesary to use that old version?

2022-10-10 04:34 UTC, zstanecic commented
Hi,

Yes, because of NVDA.

When NVDA switches to the new python, it will be reasonable to change this.

 

From: Patryk Miś ***@***.***> 
Sent: Sunday, October 9, 2022 11:33 PM
To: RHVoice/RHVoice ***@***.***>
Cc: Zvonimir Stanečić ***@***.***>; Comment ***@***.***>
Subject: Re: [RHVoice/RHVoice] Updates: Android and workflows (PR #627)

 

@PatrykMis commented on this pull request.

  _____  

In .github/workflows/ci.yml <https://github.com/RHVoice/RHVoice/pull/627#discussion_r990842800> :

>          with:
-          python-version: 3.7
+          python-version: '3.10'

Python 3.7 is almost in eol (end of life) state. Is it really nessesary to use that old version?

—
Reply to this email directly, view it on GitHub <https://github.com/RHVoice/RHVoice/pull/627#discussion_r990842800> , or unsubscribe <https://github.com/notifications/unsubscribe-auth/ACVCDE7ZUGAFNZZLAT6MBULWCM2W5ANCNFSM6AAAAAAQQTEGC4> .
You are receiving this because you commented.  <https://github.com/notifications/beacon/ACVCDE5BDR4RL3V47UFHDBDWCM2W5A5CNFSM6AAAAAAQQTEGC6WGG33NNVSW45C7OR4XAZNRKB2WY3CSMVYXKZLTORJGK5TJMV32UY3PNVWWK3TUL5UWJTSDVSWVG.gif> Message ID: ***@***.*** ***@***.***> >

2022-10-11 14:50 UTC, merged

2022-10-24 13:07 UTC, Olga-Yakovleva commented
This seems to be the reason for #658. Found by reverting Android related commits until release builds started working. I suspect the Android proguard rules replacement to the optimized set, but I am yet to test.

2022-10-24 13:42 UTC, Olga-Yakovleva commented
Yes, already done in #659.

2022-10-24 13:44 UTC, zstanecic commented
Are you going to re-enable alpha to test it, as it is relevant to releases and alpha?

 

 

From: Olga Yakovleva ***@***.***> 
Sent: Monday, October 24, 2022 3:43 PM
To: RHVoice/RHVoice ***@***.***>
Cc: Zvonimir Stanečić ***@***.***>; Comment ***@***.***>
Subject: Re: [RHVoice/RHVoice] Updates: Android and workflows (PR #627)

 

Yes, already done in #659.



—
Reply to this email directly, view it on GitHub <https://github.com/RHVoice/RHVoice/pull/627#issuecomment-1289056733> , or unsubscribe <https://github.com/notifications/unsubscribe-auth/ACVCDE7AMS3C4AF6K6AG33LWE2G5RANCNFSM6AAAAAAQQTEGC4> .
You are receiving this because you commented.  <https://github.com/notifications/beacon/ACVCDE6N2OC43O2D2SECHOLWE2G5RA5CNFSM6AAAAAAQQTEGC6WGG33NNVSW45C7OR4XAZNMJFZXG5LFINXW23LFNZ2KUY3PNVWWK3TUL5UWJTSM2VY52.gif> Message ID: ***@***.*** ***@***.***> >

2022-10-24 14:01 UTC, Olga-Yakovleva commented
Yes, but not before I have tested it myself, uploaded to Google Play, 
got it reviewed by Google, and waited just in case, so that there is no 
chance for that old release to get to users and break speech on their 
devices.